### ISSUE TITLE
Find a home on depot.galaxyproject.org for vagrant box.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#2]

**Comment by jmchilton** [comment]
@natefoo can I get some help with this - I guess I need to place them somewhere under `delirium:/srv/nginx/depot.galaxyproject.org/root`. Is that appropriate? If yes, in terms of logistics how do I  log in as sites do I need to give you an ssh key (I tried randomly sudoing and it didn't work for me).

**Comment by natefoo** [comment]
Since depot.galaxyproject.org is in EC2 I don't want to put anything huge there that could cost us a lot in transfer fees. So, I've created images.galaxyproject.org for this, which you can access via `sites@orval.galaxyproject.org:/srv/nginx/images.galaxyproject.org/root`.

**Comment by jmchilton** [comment]
Awesome just logged in and my key worked! Rebuilding a fresh instance now, thanks a bunch!
