### ISSUE TITLE
IDE should have password

### ISSUE THREAD

**Issue by kellrott** [galaxyproject/planemo-machine#22]
Right now, all it requires is an email address, which it doesn't check. It then provides command line access to the system

**Comment by jmchilton** [comment]
Yeah - I'd agree the Google version should have this - you agree the vagrant and Docker versions shouldn't though right?

**Comment by kellrott** [comment]
Actually, it might be better to just have everything require username and password for everything except for the API endpoints (which require an api key)

So in the server stanza, add something like

```
    auth_basic      "devbox";
    auth_basic_user_file  /etc/nginx/htpasswd;
```

Add a line to /etc/nginx/htpasswd for user planemo, password planemo

```
planemo:8Xvgj/h3f4hB6
```

Then add an exception (as described in http://stackoverflow.com/questions/9281564/nginx-auth-basic-for-everything-except-a-specific-location) for the /api

```
location /api {
       auth_basic off;
}
```

**Comment by jmchilton** [comment]
IDE removed.
