### ISSUE TITLE
Docker not enabled in job_conf.xml

### ISSUE THREAD

**Issue by kellrott** [galaxyproject/planemo-machine#25]
The line for 'docker_enabled' in the job_conf.xml is commented out in the current VM images.

**Comment by jmchilton** [comment]
Should be fixed by https://github.com/galaxyproject/planemo-machine/commit/3494b1f0a93a1ed8f7d1688f24ab0b96350557cf. Testing now, if things look good I will create and push out a new vagrant image.

**Comment by jmchilton** [comment]
Want to give

https://images.galaxyproject.org/planemo/20150224.box

a test? I haven't had time to try it yet but the job conf looked okay when I opened it in Docker.
