### ISSUE TITLE
/opt/galaxy/tools does not exist in GCE build

### ISSUE THREAD

**Issue by kellrott** [galaxyproject/planemo-machine#28]

**Comment by kellrott** [comment]
The directory is now built, but isn't owned but the 'ubuntu' user. So you get a 'Permission denied' if you try to do anything in it.

**Comment by jmchilton** [comment]
I think this is fixed now. Should double check and build a new GCE image?

Other good reasons to build GCE image include more planemo bug fixes and the new `restart_galaxy` command.

**Comment by kellrott** [comment]
Fixed
