### ISSUE TITLE
SMC Het Challenge Flavor

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#29]
Create a SMC Challenge Flavor of the VM
- Decide branch vs. fork vs flag.
- Pre-install `git clone https://github.com/Sage-Bionetworks/SMC-Het-Challenge.git`.
- Setup a master key and write it somewhere the submission script can pick it up automatically (e.g. `~/.smc-het.json`).

**Comment by kellrott** [comment]
I've started some of these changes at https://github.com/kellrott/planemo-machine/tree/dream-smc

**Comment by jmchilton** [comment]
Cool there is a bunch of stuff I want to pull out of the fork - I'll create an issue for it.
