### ISSUE TITLE
Configure Editors

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#34]
- [ ] Configure Emacs for Python and XML
- [ ] Configure Vim for Python and XML
- [ ] Configure nano for Python and XML

**Comment by hexylena** [comment]
vim*, please no vi.

Personally I'd even favour setting up http://vim.spf13.com/ since it comes
with lots of nice plugins.

tir. 23. jun. 2015 kl. 15.39 skrev John Chilton notifications@github.com:

**Comment by jmchilton** [comment]
@erasche - If you provide the ansible role you can configure VIM however you want :).

**Comment by hexylena** [comment]
I'll PR it whenever you add the role for vim, since I wouldn't know where to start writing an ansible role. :)

**Comment by jmchilton** [comment]
I've been dumping development box configuration stuff in here - https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml.

**Comment by hexylena** [comment]
Ah, excellent. Thanks!

**Comment by jmchilton** [comment]
So it sounds like @davebx doesn't pre-configure any of these special configurations. So as long as the ubuntu base is installed I think we will be okay - if there is a bunch of magic VIM goodness we can add though that would be awesome though too.

**Comment by hexylena** [comment]
yep, spf13 is a bundle that provides nice things like XML tag closing. I'll see what I can do to add that.

**Comment by hexylena** [comment]
That said, if there's a web IDE, wouldn't make too much sense to put a lot of effort into that... We'll see.

**Comment by jmchilton** [comment]
That is right - there is a web ide. I wonder how people are liking it. @kellrott - any thoughts on the Web IDE - is it working out and are people using it?

**Comment by jmchilton** [comment]
@erasche Added your fancy vim stuff with fc0b5e9027d7302f0624996233a5bec9f3fde5e8. Task seemed to complete without error.

**Comment by jmchilton** [comment]
Lets call this done.
