### ISSUE TITLE
basic vagrant start troubles

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo-machine#36]
I am trying to run basic vagrant planemo-machine following http://planemo.readthedocs.org/en/latest/appliance.html#launching-the-appliance-vagrant

The Galaxy at http://localhost:8010/ is up (as well as the Codebox) but in the terminal I got this
https://gist.github.com/martenson/f788d03cf005501d1438

Also if I understand it correctly the `/opt/galaxy/tools` on Vagrant should be synced to the folder I run `vagrant up` from but it is not the case. I see only `.vagrant` folder in the root.

Am I doing something wrong?

setup: Vagrant 1.7.2; OSX 10.9.5

**Comment by jmchilton** [comment]
Do you want to adjust your Vagrantfile as in galaxyproject/planemo#6a5be66. That should fix the ssh problem and I wonder if it would fix the syncing also (I am hoping that the mount is working because ssh doesn't work - logic being that the client cannot log in and setup the needed mount with an ssh connection).

**Comment by martenson** [comment]
After applying https://github.com/galaxyproject/planemo/commit/6a5be66924b917886f0a50b22e4fd3882202164f none of the services will start and log will get stuck on repeating `default: Warning: Connection timeout. Retrying...`

**Comment by jmchilton** [comment]
Really - can you `vagrant destroy` and then `vagrant up` again? If that doesn't help can you comment out the individual lines and let me know which one causes the problem.

I suppose I could do these tests myself and figure it out huh :).

**Comment by martenson** [comment]
I have been using `vagrant halt` previously. After `vagrant destroy` the Galaxy does start up but Codebox will not:

```
{
  "ok": false,
  "data": {},
  "error": "Could not run API request because user was not authenticated",
  "method": "/ide"
}
```

And the mounting will also fail:

```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'planemo'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: tool_directory_default_1435160666858_79037
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 8010 (adapter 1)
    default: 9009 => 9009 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: ubuntu
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /opt/galaxy/tools => /Users/marten/devel/training/tool_directory
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group ubuntu | cut -d: -f3` opt_galaxy_tools /opt/galaxy/tools
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g ubuntu` opt_galaxy_tools /opt/galaxy/tools

The error output from the last command was:

stdin: is not a tty
id: vagrant: no such user
uid= requires an argument (i.e. uid==<arg>)
```

**Comment by jmchilton** [comment]
I think the codebox problem is you need to use `localhost:8010/ide/` not `localhost:8010/ide` - bonus points if someone can fix that for me.

It does seem like we are making progress though. I'll look into to mounting problems. Seems odd it is looking for a vagrant user.

**Comment by jmchilton** [comment]
Seems like original issue was solved, I'll create a new one for the /ide problem.
