### ISSUE TITLE
default booting up OVA won't allow access to galaxy

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo-machine#40]
After I boot ubuntu and try to access http://localhost:8080/ I will get:

Access to Galaxy is denied

Galaxy is configured to authenticate users via an external method (such as HTTP authentication in Apache), but a username was not provided by the upstream (proxy) server. This is generally due to a misconfiguration in the upstream server.

Please contact your local Galaxy administrator.

**Comment by jmchilton** [comment]
You want just - http://localhost/. Did the docs reference 8080 somewhere?

**Comment by martenson** [comment]
Docs did not reference any url, so I tried 8080. Thanks for the clarification.

**Comment by jmchilton** [comment]
There are URLs at the end of this section - http://planemo.readthedocs.org/en/latest/appliance.html#launching-the-appliance-virtualbox-ova. Clicking them in VM should pop Galaxy, Codebox, etc....

**Comment by martenson** [comment]
Cool. I think I was looking at old version of that docs, my bad.
