### ISSUE TITLE
the OVA image needs at least 16MB video memory

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo-machine#41]
To not warn you when trying to switch to full screen.
![screenshot 2015-06-29 14 33 42](https://cloud.githubusercontent.com/assets/1814954/8415315/ee6f6cd8-1e6b-11e5-8d24-06df5f0c87d1.png)

**Comment by jmchilton** [comment]
This seems to apply only to large displays. Should we close this issue or update the documentation with a warning about large displays and a indication to increase the video memory.

**Comment by martenson** [comment]
For the workshop purposes nobody will have a big display so safe to close. I do not think this justifies a documentation note anyways.
