### ISSUE TITLE
set up OVA to do bidirectional clipboard sharing by default

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo-machine#42]
I am pretty sure this will be helpful feature to trainees.

**Comment by jmchilton** [comment]
Is there a way to bake that into the OVA?

**Comment by jmchilton** [comment]
```
        <SharedFolders/>
        <Clipboard mode="Disabled"/>
        <DragAndDrop mode="Disabled"/>
```

Found something in the OVF file - interesting.

**Comment by martenson** [comment]
According to the docs it seems that it is 'disabled for new machines'
https://www.virtualbox.org/manual/ch13.html#security_clipboard
