### ISSUE TITLE
set_metadata tool do not respect .venv

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo-machine#57]
And this breaks the upload tool. Current Image is not usable without modifications.

**Comment by afgane** [comment]
This should just a matter of updating the version of `ansible-galaxy-extras` repo to at least https://github.com/galaxyproject/ansible-galaxy-extras/commit/7b8a783cffa7dc88937669cfc722124e3a4fab31 - see PR #58.

**Comment by jmchilton** [comment]
PR merged - sorry about that @bgruening.
