### ISSUE TITLE
Augment Galaxy Masthead

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#6]
Add links to IDE, supervisor configuration.

**Comment by jmchilton** [comment]
@erasche - so this did not get done before the training - but the OVA virtualbox thing does have a bunch of shortcuts on the desktop for this sort of stuff. Doesn't help Docker or vagrant users - but the appliance docs did get updated to include these links.

**Comment by hexylena** [comment]
Sorry, yeah. sounds good.

tor. 2. jul. 2015, 07.29 skrev John Chilton notifications@github.com:

**Comment by jmchilton** [comment]
Closed in lieu of #101.
