### ISSUE TITLE
planemo test doesn't work in image

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#61]
xref #60

Docker Hub has some very fresh images with planemo 0.25.1 that have this same issue - the problem is that planemo uses Galaxy's `config/job_conf.xml` which has handlers defined that differ in name from the one used by the test framework.

**Comment by bgruening** [comment]
Urgs. But why is the build-in Galaxy working. This is also using this job_conf.xml isn't it?

**Comment by jmchilton** [comment]
Yeah - it uses that file - but it has the right handler names. Planemo is using randomly assigned names like planemo28450 for its app name I think. The fix is probably just not to fallback to Galaxy's config - I'll try to get this into planemo 0.26.0.

**Comment by bgruening** [comment]
Awesome thanks!

**Comment by bgruening** [comment]
Is there a quick fix? I suppose planemo 0.26 is not planned this week :)

**Comment by bgruening** [comment]
@jmchilton do you have any time schedule for this. @bebatut is working on new training material and I would like to include a link to a recent working image.

Thanks.

**Comment by jmchilton** [comment]
I'll release planemo 0.26 with a fix tonight. A quick work around is just not specifying `galaxy_root` in `~/.planemo.yml`.

**Comment by bgruening** [comment]
Thanks @jmchilton!

**Comment by jmchilton** [comment]
There were a few problems with the fix last night that preventing me from merging before sleep but it has been resolved I think - I will work on a release today.
