### ISSUE TITLE
Atom editor does not start up for me. 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo-machine#73]
.ova image

Shows 'loading icon' for a bit but eventually does not start.

**Comment by bgruening** [comment]
@martenson which image did you used? Do you have a link?

**Comment by martenson** [comment]
@bgruening I believe @davebx is looking at it. I used the latest from images.galaxyproject.org (2 days ago)

**Comment by martenson** [comment]
the link is https://images.galaxyproject.org/planemo/latest.ova

**Comment by davebx** [comment]
This might be fixed by #75

**Comment by martenson** [comment]
This is not resolved, behaves the same. :(
ping @davebx

**Comment by martenson** [comment]
I have found some more details, when I try to execute it from the shell

```
$ /opt/atom/atom %F
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/opt/atom/resources/atom.asar/browser/lib/init.js:142:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3
```

**Comment by martenson** [comment]
seems fixed in http://images.galaxyproject.org/planemo/20160623.ova

**Comment by jmchilton** [comment]
Okay - I have updated `latest.ova` to point to this new image - a big thanks to whoever built and uploaded it!
