### ISSUE TITLE
upload_store version update

### ISSUE THREAD

**Issue by Eduardo-Alves** [galaxyproject/planemo-machine#93]
I downloaded the planemo/interave docker image yesterday and nginx was crashing with "unknown directive upload_store". somehow it upgraded to 16.04.4 from archive.ubuntu.com

apt-cache policy nginx-common
nginx-common:
  Installed: 1.10.0-0ubuntu0.16.04.4
  Candidate: 1.10.0-0ubuntu0.16.04.4

Downgrading to 1.10.0-0ubuntu0.16.04.2ppa1 (m-vandenbeek/nginx-upload-store) fixed the problem

apt-get remove nginx-common nginx-extras
apt-get install nginx-common=1.10.0-0ubuntu0.16.04.2ppa1 
apt-get install nginx-extras=1.10.0-0ubuntu0.16.04.2ppa1 

i had to manually restart nginx, restart_galaxy didnt manage to start it

**Comment by jmchilton** [comment]
Thanks for the bug report and I'm sorry about the issue. I'll have a new Planemo machine release in the next couple months for the GCC that will hopefully address this problem.

**Comment by jmchilton** [comment]
Just encountered this myself. Ping @mvdbeek - you don't happen to have a quick fix for this do you?

**Comment by mvdbeek** [comment]
I'll have to rebuild nginx. I should really automate this.

**Comment by mvdbeek** [comment]
this is based on trusty, right?

**Comment by jmchilton** [comment]
Thanks a ton! Umm.. the Docker variant is based on Trusty - I think the VM stuff is built on 16.04 though.

**Comment by jmchilton** [comment]
There is a pin in here

```
$ /etc/apt/preferences.d/m-vandenbeek-nginx-upload-store-pin-600
Package:  *
Pin: release o=LP-PPA-m-vandenbeek-nginx-upload-store
```

Is that supposed to prevent an upgrade - it would be nice to force a particular version for the development stuff at least.

**Comment by mvdbeek** [comment]
Just a heads-up, I'm putting the finishing touches on a travis build-script that will automatically build and upload new versions of nginx using the new cron type travis builds.

**Comment by mvdbeek** [comment]
xref https://github.com/galaxyproject/starforge/pull/125, I think the package has been uploaded successfully and is building now on launchpad. Should be available later today.

**Comment by jmchilton** [comment]
Thanks a ton @mvdbeek - I really appreciate this!

**Comment by jmchilton** [comment]
I just rebuilt a container and the nginx process boots properly now. Thanks for the fix @mvdbeek  and thanks for the report @Eduardo-Alves.
